#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xEB6CCA1483FA74EC (infra-root@openstack.org)
#
Name     : stevedore
Version  : 1.25.0
Release  : 44
URL      : http://tarballs.openstack.org/stevedore/stevedore-1.25.0.tar.gz
Source0  : http://tarballs.openstack.org/stevedore/stevedore-1.25.0.tar.gz
Source99 : http://tarballs.openstack.org/stevedore/stevedore-1.25.0.tar.gz.asc
Summary  : Manage dynamic plugins for Python applications
Group    : Development/Tools
License  : Apache-2.0
Requires: stevedore-python
Requires: pbr
Requires: six
BuildRequires : configparser-python
BuildRequires : enum34-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
stevedore -- Manage dynamic plugins for Python applications
        ===========================================================

%package python
Summary: python components for the stevedore package.
Group: Default

%description python
python components for the stevedore package.


%prep
%setup -q -n stevedore-1.25.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1503155510
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
export SOURCE_DATE_EPOCH=1503155510
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python2*/*
/usr/lib/python3*/*
