#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xC36CDCB4DF00C68C (infra-root@openstack.org)
#
Name     : stevedore
Version  : 1.29.0
Release  : 45
URL      : http://tarballs.openstack.org/stevedore/stevedore-1.29.0.tar.gz
Source0  : http://tarballs.openstack.org/stevedore/stevedore-1.29.0.tar.gz
Source99 : http://tarballs.openstack.org/stevedore/stevedore-1.29.0.tar.gz.asc
Summary  : Manage dynamic plugins for Python applications
Group    : Development/Tools
License  : Apache-2.0
Requires: stevedore-python3
Requires: stevedore-license
Requires: stevedore-python
Requires: pbr
Requires: reno
Requires: six
BuildRequires : buildreq-distutils3
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python3-dev
BuildRequires : setuptools

%description
stevedore -- Manage dynamic plugins for Python applications
        ===========================================================

%package license
Summary: license components for the stevedore package.
Group: Default

%description license
license components for the stevedore package.


%package python
Summary: python components for the stevedore package.
Group: Default
Requires: stevedore-python3

%description python
python components for the stevedore package.


%package python3
Summary: python3 components for the stevedore package.
Group: Default
Requires: python3-core

%description python3
python3 components for the stevedore package.


%prep
%setup -q -n stevedore-1.29.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1532214006
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/stevedore
cp LICENSE %{buildroot}/usr/share/doc/stevedore/LICENSE
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(-,root,root,-)
/usr/share/doc/stevedore/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
