#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xB9069B1335700CDC (infra-root@openstack.org)
#
Name     : stevedore
Version  : 1.21.0
Release  : 42
URL      : http://tarballs.openstack.org/stevedore/stevedore-1.21.0.tar.gz
Source0  : http://tarballs.openstack.org/stevedore/stevedore-1.21.0.tar.gz
Source99 : http://tarballs.openstack.org/stevedore/stevedore-1.21.0.tar.gz.asc
Summary  : Manage dynamic plugins for Python applications
Group    : Development/Tools
License  : Apache-2.0
Requires: stevedore-python
Requires: pbr
Requires: six
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
===========================================================
stevedore -- Manage dynamic plugins for Python applications
===========================================================

%package python
Summary: python components for the stevedore package.
Group: Default

%description python
python components for the stevedore package.


%prep
%setup -q -n stevedore-1.21.0

%build
export LANG=C
export SOURCE_DATE_EPOCH=1489364890
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
export SOURCE_DATE_EPOCH=1489364890
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
